import Footer from "../components/footer.component"
import Header from "../components/header.component"
import React, { useEffect } from "react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"></link>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      
      <main className={styles.main}>

      <header className={styles.back}>
        
        <Image src="/back.png" alt="Vercel Logo" width={40} height={40} />
            
          </header>
        <h1 className={styles.title}>Nosotros
        
        </h1>

        <div className={styles.columns2}>
       
        <div className={styles.column2}> 
        <a href="https://nextjs.org/docs" className={styles.card}>
        <Image src="/persona.jpg" alt="Vercel Logo" width={200} height={300} />

            <p>Rodrigo Salazar Vega

            </p>
          </a>
        </div>
        <div className={styles.column2}> 
        <Image src="/persona.jpg" alt="Vercel Logo" width={200} height={300} />

        <a href="https://nextjs.org/docs" className={styles.card}>
            <p>Juan de Diego rojas Saldarriaga

            </p>
          </a>
        </div>
        <div className={styles.column2}> 
        <Image src="/persona.jpg" alt="Vercel Logo" width={200} height={300} />

        <a href="https://nextjs.org/docs" className={styles.card}>
            <p>Luis Manuel Mondoñedo Cabanillas

            </p>
          </a>
        </div>

        <div className={styles.column2}> 
        <Image src="/persona.jpg" alt="Vercel Logo" width={200} height={300} />

        <a href="https://nextjs.org/docs" className={styles.card}>
            <p>Leonardo Guillermo Falcon Choque

            </p>
          </a>
        </div>
          
          
          
        </div>
      </main>  
    </div>
  );
}
